### ISSUE TITLE
Error! Unable to open database: SQLSTATE[HY000] [14] unable to open database file

### ISSUE THREAD

**Issue by michelpy** [gmazoyer/looking-glass#177]
When clicking on 'Enter' for any request, I get this :
Error! Unable to open database: SQLSTATE[HY000] [14] unable to open database file

I temporarily solved this by adding :
$config ['antispam']['enabled'] = false;
in config.php
I think it's the new antispam option, there is no database for it in the zip file.

Not a big deal, but could be fixed in next release.

**Comment by gmazoyer** [comment]
Even-though the database file is not provided, it should be created automatically at the first request. This may indicate that the web server user does not have the permission to write a file in the looking glass directory.

**Comment by michelpy** [comment]
I'll check anything you'd like me too.
I installed apache2 everything by default, like "apt install apache2", did not give any extra permissions.
[En Français aussi si tu veux]

**Comment by michelpy** [comment]
I put all the files in /var/www/html

**Comment by gmazoyer** [comment]
There are few checks to perform to make sure that the SQLite database can be created and used.

1. Make sure the looking glass directory is writeable by the web server's user (that mostly means checking directory/file ownership and permissions)
2. Make sure that you have the PHP SQLite extension installed
3. Make sure that PHP PDO has been compiled with the SQLite driver (if you use a Debian based distro that shouldn't be a problem)

Perhaps it's due to the PHP version, although I would find that surprising.
