### ISSUE TITLE
Increase time for SPAM

### ISSUE THREAD

**Issue by aelxdc** [gmazoyer/looking-glass#181]
Hi, 
I need to increase the ANTISPAM time for every consult, how can I do that? I see the file include/antispam.php but I can't find the parameter to do this..

**Comment by incentre** [comment]
Had the same problem. If you're looking to increase/decrease this, the base is in antispam.php
`  private function no_query_period($degree) {
    return time() + intval(pow($degree, 2.5));
  }
`

Instead of that I simply added a whitelist to config.php:
`
$nospam = array(
	'111.111.111.111',
	'2.2.2.2'
);
`
Then in antispam.php made the following change:
`
  public function check_spammer($remote_address) {
	global $nospam;
	if (in_array($remote_address, $nospam)) {
		return;
	}
`

Quick and dirty, but it exempts our in-house IPs from the spam check.

**Comment by aelxdc** [comment]
> Had the same problem. If you're looking to increase/decrease this, the base is in antispam.php ` private function no_query_period($degree) { return time() + intval(pow($degree, 2.5)); }`
> 
> Instead of that I simply added a whitelist to config.php: `$nospam = array( '111.111.111.111', '2.2.2.2' );` Then in antispam.php made the following change: `public function check_spammer($remote_address) { global $nospam; if (in_array($remote_address, $nospam)) { return; }`
> 
> Quick and dirty, but it exempts our in-house IPs from the spam check.

Thanks !
So, if I want to increase the interval for all IPs, just edit the 2.5 on the antispam.php?

**Comment by lanrat** [comment]
All spam checks can be disabled by adding the following line to `config.php`.

```php
$config['antispam']['enabled'] = false;
```
